-- ThreatScope Supabase schema
-- Apply this in the Supabase SQL Editor for the first migration pass.

create table if not exists public.alerts (
    id bigint generated by default as identity primary key,
    type text not null,
    src_ip text not null,
    dst_ip text not null,
    severity text not null check (severity in ('LOW', 'MEDIUM', 'HIGH')),
    message text not null,
    timestamp timestamptz not null default timezone('utc', now()),
    user_id uuid references auth.users(id) on delete cascade
);

alter table public.alerts
    add column if not exists user_id uuid references auth.users(id) on delete cascade;

create index if not exists alerts_timestamp_idx on public.alerts (timestamp desc);
create index if not exists alerts_severity_idx on public.alerts (severity);
create index if not exists alerts_type_idx on public.alerts (type);
create index if not exists alerts_src_ip_idx on public.alerts (src_ip);
create index if not exists alerts_user_id_idx on public.alerts (user_id);

alter table public.alerts enable row level security;

revoke select on public.alerts from anon;
revoke select on public.alerts from public;
grant select on public.alerts to authenticated;
grant select, insert, update, delete on public.alerts to service_role;

drop policy if exists "Allow read access to alerts" on public.alerts;
drop policy if exists "authenticated can read alerts" on public.alerts;
create policy "authenticated can read alerts"
on public.alerts
for select
to authenticated
using (auth.uid() = user_id);

do $$
begin
    if not exists (
        select 1
        from pg_publication_tables
        where pubname = 'supabase_realtime'
          and schemaname = 'public'
          and tablename = 'alerts'
    ) then
        alter publication supabase_realtime add table public.alerts;
    end if;
end $$;
