-- ThreatScope Supabase schema
-- Apply this in the Supabase SQL Editor for the first migration pass.

create table if not exists public.alerts (
    id bigint generated by default as identity primary key,
    type text not null,
    src_ip text not null,
    dst_ip text not null,
    severity text not null check (severity in ('LOW', 'MEDIUM', 'HIGH')),
    message text not null,
    timestamp timestamptz not null default timezone('utc', now())
);

create index if not exists alerts_timestamp_idx on public.alerts (timestamp desc);
create index if not exists alerts_severity_idx on public.alerts (severity);
create index if not exists alerts_type_idx on public.alerts (type);
create index if not exists alerts_src_ip_idx on public.alerts (src_ip);

alter table public.alerts enable row level security;

grant select on public.alerts to anon, authenticated;

drop policy if exists "Allow read access to alerts" on public.alerts;
create policy "Allow read access to alerts"
on public.alerts
for select
to anon, authenticated
using (true);

alter publication supabase_realtime add table public.alerts;
